project:
  type: website
  output-dir: docs

website:
  title: "Sabina Peterson Rajalingam's Website"
  navbar:
    right:
    - text: About Me
      href: about.html
    - text: Data Viz
      menu: 
      - text: Dog Breed Ranks
        href: breed_rank.html
      - text: Simpsons Episodes
        href: simpson_episodes.html

format:
  html:
    theme: cosmo
      - cosmo
      - brand
    css: styles.css
    toc: true



